2025-08-03 16:43:55 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:44:04 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:44:04 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:44:06 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:44:44 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:44:44 - pca_module - ERROR - realizar_pca:99 - Error de validación: 'DataValidator' object has no attribute 'validate_dataframe_for_pca'
2025-08-03 16:50:22 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-03 16:50:22 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-03 16:50:30 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-03 16:50:30 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-03 16:50:30 - pca_gui - ERROR - wrapper:114 - Error in run_series_analysis
Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_gui.py", line 112, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\performance_optimizer.py", line 291, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_gui.py", line 166, in run_series_analysis
    results = PCAAnalysisLogic.run_series_analysis_logic(cfg, imputation_strategy=estrategia, imputation_params=params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_logic.py", line 69, in run_series_analysis_logic
    sugg_90 = np.where(cum_evr >= 0.90)[0]
                       ^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
2025-08-03 16:50:43 - pca_gui - ERROR - wrapper:114 - Error in run_series_analysis
Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_gui.py", line 112, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\performance_optimizer.py", line 291, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_gui.py", line 166, in run_series_analysis
    results = PCAAnalysisLogic.run_series_analysis_logic(cfg, imputation_strategy=estrategia, imputation_params=params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_logic.py", line 69, in run_series_analysis_logic
    sugg_90 = np.where(cum_evr >= 0.90)[0]
                       ^^^^^^^^^^^^^^^
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
2025-08-03 16:52:53 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-03 16:52:53 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-03 16:53:31 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 1 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-03 16:53:31 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 1 Sugerencia: Agrega más observaciones al dataset
2025-08-03 16:53:31 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-03 16:54:13 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-03 16:54:13 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:34:55 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:34:56 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:38:22 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:38:22 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:41:28 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:41:28 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:46:19 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:46:19 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:47:31 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:47:31 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:48:34 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:48:34 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:49:38 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:49:38 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:51:23 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:51:23 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:53:23 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:53:23 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-07 11:58:18 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-07 11:58:18 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 13:52:54 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 1 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-09 13:52:54 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 1 Sugerencia: Agrega más observaciones al dataset
2025-08-09 13:52:54 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-09 21:17:43 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:17:43 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:22:05 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:22:05 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:22:16 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:22:16 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:22:26 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:22:26 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:27:29 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:27:29 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:27:38 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:27:38 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:27:53 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 1 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:27:53 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 1 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:27:53 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-09 21:28:45 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:28:45 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:30:37 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:30:37 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:30:48 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 1 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:30:48 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 1 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:30:48 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-09 21:31:03 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:31:03 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 21:39:03 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 2 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:39:03 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 2 Sugerencia: Agrega más observaciones al dataset
2025-08-09 21:39:03 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-09 21:41:34 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 21:41:34 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 22:09:50 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 22:09:50 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

2025-08-09 22:10:02 - data_validation - ERROR - _log_issue:51 - DataFrame estandarizado tiene 1 filas, se requieren al menos 3 Sugerencia: Agrega más observaciones al dataset
2025-08-09 22:10:02 - data_validation - ERROR - _log_issue:51 - PCA requiere al menos 3 observaciones, DataFrame estandarizado tiene 1 Sugerencia: Agrega más observaciones al dataset
2025-08-09 22:10:02 - pca_module - ERROR - realizar_pca:99 - Validación fallida: Error desconocido
2025-08-09 22:25:09 - pca_module - ERROR - realizar_pca:166 - Error durante la ejecución del ACP: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.
2025-08-09 22:25:09 - pca_module - ERROR - realizar_pca:167 - Traceback (most recent call last):
  File "C:\Users\messi\OneDrive\Escritorio\escuela\Servicio Social\Python\PCA\pca_module.py", line 151, in realizar_pca
    pca_data = pca_model.fit_transform(df_procesar_pca)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\utils\_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
  File "C:\Python312\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
  File "C:\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of PCA must be an int in the range [0, inf), a float in the range (0.0, 1.0), a str among {'mle'} or None. Got 'auto' instead.

